[versions]
agp = "8.4.1"
kotlin = "1.9.22"
ksp = "1.9.22-1.0.18"
coreKtx = "1.13.1"

androidxActivity = "1.9.0"
androidxLifecycle = "2.7.0"
androidxComposeBom = "2024.05.00"
androidxComposeCompiler = "1.5.8"
androidxComposeUiManifest = "1.6.7"
androidxComposeMaterial3 = "1.2.1"
androidxPagingCompose = "3.3.0"

androidxComposeUiTest = "1.7.0-beta01"

coil = "2.6.0"
hilt = "2.51"
navigationHilt = "1.5.0"
okhttp = "4.12.0"
retrofit = "2.9.0"
timberVersion = "5.0.1"
secretsVersion = "2.0.1"
jodaTimeVersion = "2.10.9.1"

ktlintVersion = "11.3.2"
deteKtVersion = "1.23.0-RC3"
jacoco = "0.8.7"

junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.12.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtimeTesting = { group = "androidx.lifecycle", name = "lifecycle-runtime-testing", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "androidxPagingCompose" }

androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "androidxComposeUiTest" }
androidx-compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }

navigation-hilt = { group = "dev.olshevski.navigation", name = "reimagined-hilt", version.ref = "navigationHilt" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timberVersion" }
joda-time = { group = "net.danlew", name = "android.joda", version.ref = "jodaTimeVersion" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

# Dependencies of the included build-config
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
#ktlint-gradlePlugin = { group = "org.jlleitschuh.gradle.ktlint", name = "org.jlleitschuh.gradle.ktlint.gradle.plugin", version.ref = "ktlintVersion" }
detekt-gradlePlugin = { group = "io.gitlab.arturbosch.detekt", name = "io.gitlab.arturbosch.detekt.gradle.plugin", version.ref = "deteKtVersion" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secretsVersion" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintVersion" }
deteKt = { id = "io.gitlab.arturbosch.detekt", version.ref = "deteKtVersion" }

# Plugins defined by this project
codewars-android-application = { id = "codewars.android.application", version = "unspecified" }
codewars-android-application-compose = { id = "codewars.android.application.compose", version = "unspecified" }
codewars-android-application-jacoco = { id = "codewars.android.application.jacoco", version = "unspecified" }
codewars-android-application-ktlint = { id = "codewars.android.application.ktlint", version = "unspecified" }
codewars-android-application-detekt = { id = "codewars.android.application.detekt", version = "unspecified" }
codewars-android-feature = { id = "codewars.android.feature", version = "unspecified" }
codewars-android-library = { id = "codewars.android.library", version = "unspecified" }
codewars-android-library-compose = { id = "codewars.android.library.compose", version = "unspecified" }
codewars-android-library-jacoco = { id = "codewars.android.library.jacoco", version = "unspecified" }
codewars-jvm-library = { id = "codewars.jvm.library", version = "unspecified" }
codewars-android-hilt = { id = "codewars.android.hilt", version = "unspecified" }
